name: ai_commit
description: Dart CLI for generate commit messages with OpenAI
version: 0.0.1
repository: https://github.com/thitlwincoder/ai_commit
issue_tracker: https://github.com/thitlwincoder/ai_commit/issues
environment:
  sdk: ">=3.0.0 <4.0.0"

funding:
  - https://paypal.me/thitlwin312
  - https://ko-fi.com/thitlwincoder

topics:
  - ai
  - commit
  - openai

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  dart_openai: ^5.1.0
  hive: ^2.2.3
  http: ^1.2.2
  mason_logger: ^0.3.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  ai_commit:
